#!/bin/bash

SHNAME=$(basename $0)

testExit() {
    TMPDIR=$(mktemp -d "/tmp/${SHNAME}-XXXXXX")

    cat > $TMPDIR/config <<EOF
EMAIL_NOTIFY="NEVER"
EOF
    
    ./mini-ci -d $TMPDIR -F quit
    assertEquals "Wrong return code" $? 0 || return

    rm -rf $TMPDIR
}

. shunit2
