#!/bin/bash

SHNAME=$(basename $0)

testRunTasks() {
    TMPDIR=$(mktemp -d "/tmp/${SHNAME}-XXXXXX")
    WORK_DIR=$TMPDIR/workspace

    cat > $TMPDIR/config <<EOF
EMAIL_NOTIFY="NEVER"
REPO_HANDLER=""
WORK_DIR="./workspace"
EOF

    mkdir -p $TMPDIR/workspace
    mkdir -p $TMPDIR/tasks.d
    cat > $TMPDIR/tasks.d/01-good-task <<EOF
#!/bin/sh
touch good-task
EOF
    cat > $TMPDIR/tasks.d/02-bad-task <<EOF
#!/bin/sh
exit 1
EOF

    cat > $TMPDIR/tasks.d/03-worse-task <<EOF
#!/bin/sh
touch worse-task
EOF
    chmod +x $TMPDIR/tasks.d/*

    ./mini-ci -d $TMPDIR -D -F tasks quit
    assertEquals "Wrong return code" 0 $?

    assertTrue "Good task didn't execute" "[ -f '${WORK_DIR}/good-task' ]"
    assertTrue "run/1 directory missing" "[ -d '${TMPDIR}/run/1/' ]"
    assertTrue "Good task didn't have log file" "[ -f '${TMPDIR}/run/1/task-01-good-task.log' ]"
    assertTrue "Worse task did execute" "[ ! -f '${WORK_DIR}/worse-task' ]"

    rm -rf $TMPDIR
}

. shunit2
