#!/bin/bash

SHNAME=$(basename $0)

testRunTasks() {
    TMPDIR=$(mktemp -d "/tmp/${SHNAME}-XXXXXX")
    WORKSPACE=$TMPDIR/workspace

    cat > $TMPDIR/config <<EOF
EMAIL_NOTIFY="NEVER"
REPO_HANDLER=""
EOF

    mkdir -p $TMPDIR/workspace
    mkdir -p $TMPDIR/tasks.d
    cat > $TMPDIR/tasks.d/01-env <<EOF
#!/bin/sh
env | sort > env.txt
EOF

    cat > $TMPDIR/tasks.d/02-good-task <<EOF
#!/bin/sh
touch good-task
EOF
    cat > $TMPDIR/tasks.d/03-bad-task <<EOF
#!/bin/sh
exit 1
EOF

    cat > $TMPDIR/tasks.d/04-worse-task <<EOF
#!/bin/sh
touch worse-task
EOF
    chmod +x $TMPDIR/tasks.d/*

    ./mini-ci -d $TMPDIR -D -F tasks quit
    assertEquals "Wrong return code" 0 $?

    assertTrue "Env task didn't execute" "[ -f '${WORKSPACE}/env.txt' ]"
    assertTrue "BUILD_DISPLAY_NAME not set" "egrep '^BUILD_DISPLAY_NAME=#1$' ${WORKSPACE}/env.txt"
    assertTrue "BUILD_ID not set" "egrep '^BUILD_ID=..+$' ${WORKSPACE}/env.txt"
    assertTrue "BUILD_NUMBER not set" "egrep '^BUILD_NUMBER=1$' ${WORKSPACE}/env.txt"
    assertTrue "BUILD_TAG not set" "egrep '^BUILD_TAG=..+$' ${WORKSPACE}/env.txt"
    assertTrue "JOB_DIR not set" "egrep '^JOB_DIR=..+$' ${WORKSPACE}/env.txt"
    assertTrue "JOB_NAME not set" "egrep '^JOB_NAME=..+$' ${WORKSPACE}/env.txt"
    assertTrue "REPO_URL not set" "egrep '^REPO_URL=$' ${WORKSPACE}/env.txt"
    assertTrue "WORKSPACE not set" "egrep '^WORKSPACE=..+$' ${WORKSPACE}/env.txt"
    assertTrue "Good task didn't execute" "[ -f '${WORKSPACE}/good-task' ]"
    assertTrue "run/1 directory missing" "[ -d '${TMPDIR}/run/1/' ]"
    assertTrue "Good task didn't have log file" "[ -f '${TMPDIR}/run/1/task-02-good-task.log' ]"
    assertTrue "Worse task did execute" "[ ! -f '${WORKSPACE}/worse-task' ]"

    rm -rf $TMPDIR
}

. shunit2
