#!/bin/bash

SHNAME=$(basename $0)
CURDIR=$PWD

testPoll() {
    TMPDIR=$(mktemp -d "/tmp/${SHNAME}-XXXXXX")
    REPO_URL=$TMPDIR/repo.git
    WORK_DIR=$TMPDIR/workspace
    POLL_LOG=$TMPDIR/poll.log
    
    git --bare init $REPO_URL || return
    
    cat > $TMPDIR/config <<EOF
EMAIL_NOTIFY="NEVER"
REPO_HANDLER=git
REPO_URL=$REPO_URL
POLL_LOG=$POLL_LOG
EOF

    (cd $TMPDIR && $CURDIR/mini-ci -F poll quit)
    assertEquals "Wrong return code" $? 0

    assertTrue "Did not checkout repository" "[ -d '${WORK_DIR}/.git' ]"
    assertTrue "Did not create $(basename "${POLL_LOG}")" "[ -f '${POLL_LOG}' ]"

    if [ -f "${POLL_LOG}" ]; then
        LINES=$(wc -l < "$POLL_LOG")
        assertTrue "Not enough lines in $POLL_LOG ($LINES)" "[ $LINES -gt 0 ]"
    fi
    rm -rf $TMPDIR
}


testInitialUpdate() {
    TMPDIR=$(mktemp -d "/tmp/${SHNAME}-XXXXXX")
    REPO_URL=$TMPDIR/repo.git
    WORK_DIR=$TMPDIR/workspace

    git --bare init $REPO_URL || return
    
    cat > $TMPDIR/config <<EOF
EMAIL_NOTIFY="NEVER"
REPO_HANDLER=git
REPO_URL=$REPO_URL
EOF

    (cd $TMPDIR && $CURDIR/mini-ci -F update quit)
    assertEquals "Wrong return code" $? 0

    assertTrue "Did not checkout repository" "[ -d '${WORK_DIR}/.git' ]"
    rm -rf $TMPDIR
}

testNextUpdate() {
    TMPDIR=$(mktemp -d "/tmp/${SHNAME}-XXXXXX")
    REPO_URL=$TMPDIR/repo
    WORK_DIR=$TMPDIR/workspace

    git init $REPO_URL || return
    
    cat > $TMPDIR/config <<EOF
EMAIL_NOTIFY="NEVER"
REPO_HANDLER=git
REPO_URL=$REPO_URL
EOF

    (cd $TMPDIR && $CURDIR/mini-ci -F update quit)
    assertEquals "Wrong return code" $? 0

    assertTrue "Did not checkout repository" "[ -d '${WORK_DIR}/.git' ]"

    (cd $REPO_URL;
     date > $REPO_URL/test-file;
     git add test-file;
     git commit test-file -m 'Added test-file')

    (cd $TMPDIR && $CURDIR/mini-ci -F update quit)
    assertEquals "Wrong return code" $? 0

    assertTrue "Did not find new file" "[ -f '${WORK_DIR}/test-file' ]"
    
    rm -rf $TMPDIR
}


. shunit2
